### ISSUE TITLE
How to config  this plug

### ISSUE THREAD

**Issue by lueliu** [batistutaluke/GomeBigDataKafkaToDB#1]
I want to sent data in kafka topic to RDB. But I don't know how to config whit this plug.

**Comment by batistutaluke** [comment]
This is a part of mysql to oracle synchronization chain, just from kafka to oracle.  The messages from kafka topic  are operations of row data in mysql, and the format is custom, so it may be not suitable for you. This plug is not complex, just convert the message from kafka to sql, then modify oracle via jdbc.
